### ISSUE TITLE
Provide Guidance for Windows Anaconda Installation

### ISSUE THREAD

**Issue by jvallentine1211** [dlab-berkeley/Python-Fundamentals-Legacy#11]
While installing Anaconda on Windows 10, I get this pop-up and I am not sure what I should do. Should I keep the defaults or should I change something in the advanced options of the installation? It would help to have some documentation about what to do when I see this screen.

![Anaconda](https://user-images.githubusercontent.com/76078876/102939139-8859c380-4462-11eb-853c-d4d422970ef4.PNG)

**Comment by aculich** [comment]
Thanks for adding this, @jvallentine1211 !

**Comment by aculich** [comment]
We probably want to recommend that people accept the defaults, but that means that it will register the Anaconda3 version of Python as their default in most (but maybe not all!) places, however if they have already installed some other version of Python some other (non-Anaconda) way, there could be conflicts.
