### ISSUE TITLE
Update installation instructions to say Python 3.7 or higher

### ISSUE THREAD

**Issue by dlab-frontdesk** [dlab-berkeley/Python-Fundamentals-Legacy#23]
The instructions currently specify Python 3.7 exactly, which confuses some detail-oriented people because they can no longer find the older 3.7 now that Anaconda provides a newer 3.8 version of Python.

This confusion can be avoid by updating the instructions everywhere (not just in this repo, but we should check for this elsewhere, too) by just saying `Python 3.7 or higher`.

---------- Forwarded message ---------
From: D-Lab Frontdesk <dlab-frontdesk@berkeley.edu>
Date: Tue, Oct 26, 2021 at 2:17 PM
Subject: Re: Python 3.7 Installation problem?
To: Matt Nolan <mpnolan@lbl.gov>

Hi Matt, the instructions should say Python 3.7 or higher. Thanks for pointing out the confusion!

On Tue, Oct 26, 2021 at 10:08 AM Matt Nolan <mpnolan@lbl.gov> wrote:
The instructions for the class seem to be out of date.

The page you pointed to contains places to download Python 3.8 but not Python 3.7.

Python 3.7 isn't listed in the archive

Maybe its the notes in the google calendar event that are mistaken it says 3.7, should it say 3.8?

Can you add some clarity about what exactly I am supposed to download to be prepared for the class today? thanks

Software Requirements: Installation Instructions for Python Anaconda

D-Lab Python Fundamentals
This is the repository for D-Lab's introductory Python-Fundamentals workshop series. Laptop, Internet connection, and Zoom account required.

Workshop goals
There are four folders (one for each day) that contain the notebooks we will walk through for each day:

Day_1 - Running Python, Jupyter Notebooks, variables assignment, data type conversion, working with strings, built-in functions

Day_2 - Lists, for-loops, conditional statements, writing your own functions, scope

Day_3 - Dictionaries, reading and writing data from and to files, installing and importing libraries, debugging errors, list comprehensions, beautiful code

Day_4 - Python application for information retrieval. You will extract targeted information from a text data set of United Nations documents to generate tabular data in a .csv file suitable for subsequent statistical analysis. Everything needed for this exercise is covered in Days 1, 2, and 3.

Installation Instructions
Download and install Python Anaconda distribution 3.7 and the workshop materials to get started. Before Part 1 be sure to:

Download and install Python Anaconda distrubtion 3.7 --> Click "Download" and then click 64-bit "Graphical Installer" for your current operating system.

====

I searched the page and Download isn't found.  Towards the bottom of the link to 3.7 installation its python 3.8  downloads

**Comment by kjhogue** [comment]
typo in spelling of "distribution" in this line: "Download and install Python Anaconda distrubtion 3.7 --> Click "Download" and then click 64-bit "Graphical Installer" for your current operating system." Very interested to find out if notebooks work properly in current version of Anaconda.
