### ISSUE TITLE
In accumulator patterns, change variable names to be more informatives

### ISSUE THREAD

**Issue by emilygrabowski** [dlab-berkeley/Python-Fundamentals-Legacy#66]
for example: for number in numbers --> for n in numbers

**Comment by pssachdeva** [comment]
What PR closed this (and the other issues)? I don't see an associated PR for it.

**Comment by emilygrabowski** [comment]
Do you see it now?

**Comment by pssachdeva** [comment]
Yes, I see it! See my note there about how you can close issues when you merge the PR.
