### ISSUE TITLE
13_Pandas - minor typo in Challenge 4

### ISSUE THREAD

**Issue by liuange** [dlab-berkeley/Python-Fundamentals-Legacy#75]
Directions state:  

>  To do this, we set the first layer equal to the variable `fig`. This represents our plot. All of our plots thus far have had a single layer. To include multiple layers in a plot, we simply include the argument `ax=fig` in any subsequent layers. This tells `pandas` to put new layers on the original plot rather than to make a new plot.
> 1. Make three different sub-DataFrames, one for each species, using `.loc[]` and a Boolean mask. (**Hint:** This is the solution to Challenge 3)
>**2. Plot the first layer and set it equal to `fig`.**
>**3. Plot subsequent layers. Use a different color for each species (look at the documentation for the name of the color parameter). Some possible colors to use are `'green'`, `'red'`, `'purple'`, `'black'`, etc. (Remember to include the argument `ax=fig`!)**
>4. Do you notice a pattern in culmen measurements based on species? What other elements for the plot would be helpful for interpreting it?

However, solution sets all three .plot() calls to ax. Should update the first call to fig = , and update the ax=ax arguments to ax=fig for the next two .plot() calls.

**Comment by sociologyquinn** [comment]
adding a few typos in first paragraph of challenge 4: 

a) typo in first line ("culemtn") ; 

b) typo in "visualize this pattern if is present" should say something like "pattern if IT is present"
